name: seismoslide
channels:
 - conda-forge
dependencies:
 - python=3.11
 - numpy=1.24
 - matplotlib=3.7
 - obspy=1.4
 - pytorch-cpu=2.0
 - cartopy=0.21                 # Not sure if I need this.
 - python-graphviz=0.20
 - pip=23.2.1
 - pip:
   - seisbench
 - pytest=7.3.1
 - wandb=0.16.1
 - pandas=2.1.4
 # Dev stuff
 - python-lsp-server
 - ipython=8.16
 - pyflakes=3.0.1
 - black=23.9.1
