name: seismoslide
channels:
 - conda-forge
 - pytorch-nightly
dependencies:
 - python=3.11
 - numpy=1.24
 - matplotlib=3.7
 - obspy
 - pytorch=2.3.0.dev20240129
 - cartopy=0.21                 # not sure if i need this.
 - python-graphviz=0.20
 - pip=23.2.1
 - pip:
   - seisbench
 - pytest=7.3.1
 - wandb=0.16.2
 - pandas=2.1.4
 # - bottleneck=1.3.7
 - scikit-learn
 # Dev stuff
 - python-lsp-server
 - ipython=8.16
 - pyflakes=3.0.1
 - black
