name: seismoslide
channels:
 - conda-forge
dependencies:
 - python=3.11
 - numpy=1.24
 - matplotlib=3.7
 - obspy=1.4
 - pytorch-cpu=2.0
 - cartopy=0.21                 # Not sure if I need this.
 - pip=23.2.1
 - pip:
   - seisbench
 # Dev stuff
 - python-lsp-server=1.7.4
 - ipython=8.14
 - pyflakes=3.0.1
